<a href="https://colab.research.google.com/github/AhmadMujtaba200210/ML-mathematics-fundamental/blob/develop/Scalars.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### scalar rank 0 tensors

In [ ]:
x=5
x

5

In [ ]:
y=5.5
y

5.5

In [ ]:
type(y)


float

## Scalars in Pytorch

In [ ]:
import torch

In [ ]:
x_pt= torch.tensor(30) # specifying datatype is optional i.e dtype= torch.flaot32
x_pt

tensor(30)

#### It has zero dimension

In [ ]:
x_pt.shape 

torch.Size([])

## Scalars in TensorFlow

In [8]:
import tensorflow as tf

In [10]:
x_tf= tf.Variable(25) # we can specify the datatype of scalar tensors i.e dtype = tf.int32
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=25>

#### It has zero dimension

In [ ]:
x_tf.shape

In [13]:
y_tf = tf.Variable(20)
y_tf

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>

In [14]:
y_tf.shape

TensorShape([])

In [15]:
x_tf+y_tf

<tf.Tensor: shape=(), dtype=int32, numpy=45>

In [16]:
sum_tf= tf.add(x_tf,y_tf)
sum_tf

<tf.Tensor: shape=(), dtype=int32, numpy=45>

In [17]:
sum_tf.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=45>>

In [18]:
float_tf=tf.Variable(25,dtype=tf.float16)
float_tf

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=25.0>