In [1]:
import torch

In this notebook, we calculate the gradient of quadratic cost with respect to a straight-line regression model's parameters.

In [9]:
xs = torch.tensor([0,1,2,3,4,5,6,7]) #no of milimeters for alzimer drug given to patient

In [4]:
ys = torch.tensor([1.86, 1.31, .62, .33, .09, -.67, -1.23, -1.37]) #outcome of treatment by drug i.e. forgetfullness is decreased as dosage increased

Slope of Line given by: $y = mx +b$

In [5]:
def regression(x,m,b):
    return m*x+b

In [6]:
m = torch.tensor([0.9]).requires_grad_()

In [7]:
b = torch.tensor([0.1]).requires_grad_()

To keep the partial derivatives as simple as possible, let's move forward with a single instance $i$ from the eight possible data points: 

In [10]:
i = 7
x = xs[i]
y = ys[i]

In [11]:
x

tensor(7)

In [13]:
y

tensor(-1.3700)

**Step 1**: Forward pass

In [15]:
yhat = regression(x,m,b)
yhat

tensor([6.4000], grad_fn=<AddBackward0>)

**Step 2**: Compare $\hat{y}$ with true $y$ to calculate cost $C$

In the *Regression in PyTorch* notebook, we used mean-squared error, which averages quadratic cost over multiple data points. With a single data point, here we can use quadratic cost alone. It is defined by: $$ C = (\hat{y} - y)^2 $$

In [16]:
def mean_squared_error(yhat,y):
    return torch.square(yhat-y)

In [17]:
C = mean_squared_error(yhat,y)
C

tensor([60.3729], grad_fn=<PowBackward0>)

**Step 3**: Use autodiff to calculate gradient of $C$ w.r.t. parameters

In [18]:
C.backward()

In [19]:
m.grad # partial derivative w.r.t m

tensor([108.7800])

In [21]:
b.grad # partial derivative w.r.t b

tensor([15.5400])