<a href="https://colab.research.google.com/github/AhmadMujtaba200210/ML-mathematics-fundamental/blob/develop/Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
x=np.array([25,2,5], dtype=np.float16)
x

array([25.,  2.,  5.], dtype=float16)

In [4]:
len(x)

3

In [6]:
x.shape

(3,)

In [7]:
type(x)

numpy.ndarray

In [8]:
x[0]

25.0

In [9]:
type(x[0])

numpy.float16

#### Transposing vector using numpy

In [11]:
# no effect on a regular 1-D array
x_t=x.T
x_t

array([25.,  2.,  5.], dtype=float16)

In [12]:
x_t.shape

(3,)

In [18]:
# zero vectors
z=np.zeros(3)
z

array([0., 0., 0.])

#### Vectors in PyTorch and TensorFlow


# Matrix

In [13]:
y=np.array([[25,2,5]],dtype=np.float32)
y

array([[25.,  2.,  5.]], dtype=float32)

In [14]:
len(y)

1

In [15]:
y.shape

(1, 3)

In [16]:
# transposing the vector having change in shape as it is 2D array
y_t=y.T
y_t

array([[25.],
       [ 2.],
       [ 5.]], dtype=float32)

In [17]:
y_t.shape

(3, 1)